// Shared dataset for caseflows concepts. 41 cases.
window.CASES = [
  {fol:1, name:"Allegations of Genocide", italic:"Ukraine v Russia · 32 intervening states", forum:"ICJ", forumLabel:"ICJ", docket:"GL 182", filed:"2022-02-26", year:"2022", status:"pending", statusLabel:"pending merits", theme:["civilian","territory"], amount:null, amountLbl:"", note:"32 states intervene — the largest in ICJ history.", milestones:[["2022-03-16","Provisional measures (13–2): suspend military operations",true],["2024-02-02","Preliminary objections — narrow jurisdiction",false],["2027-12-07","Rejoinder due",false]]},
  {fol:2, name:"Ukraine v Russia (CERD + ICSFT)", italic:"Terrorism Financing & Racial Discrimination Conventions", forum:"ICJ", forumLabel:"ICJ", docket:"GL 166", filed:"2017-01-16", year:"2017", status:"decided", statusLabel:"merits 2024", theme:["civilian","territory"], amount:null, amountLbl:"", note:"First ICJ merits ruling on the war. No compensation awarded.", milestones:[["2017-04-19","Provisional measures (CERD)",false],["2024-01-31","Merits judgment",true]]},
  {fol:3, name:"Russia v Australia & Netherlands", italic:"Article 84 appeal of the ICAO Council MH17 decision", forum:"ICJ", forumLabel:"ICJ", docket:"GL 201", filed:"2025-09-18", year:"2025", status:"pending", statusLabel:"preliminary phase", theme:["civilian"], amount:null, amountLbl:"", note:"First Article 84 case to be litigated to its end.", milestones:[["2025-09-18","Application filed",true]]},
  {fol:4, name:"Ukraine v Russia (re Crimea) [GC]", italic:"Inter-state — occupation of Crimea since Feb 2014", forum:"ECtHR", forumLabel:"ECtHR", docket:"20958/14, 38334/18", filed:"2014-03-13", year:"2014", status:"decided", statusLabel:"violations found 2024", theme:["civilian","territory"], amount:null, amountLbl:"", note:"Articles 2, 3, 5, 6, 8–11, 14, 18, P1-1, P1-2, P4-2 all violated.", milestones:[["2021-01-14","Admissibility — jurisdiction confirmed",false],["2024-06-25","Merits judgment — unanimous",true]]},
  {fol:5, name:"Ukraine and the Netherlands v Russia [GC]", italic:"Eastern Ukraine, MH17, and the full-scale invasion", forum:"ECtHR", forumLabel:"ECtHR", docket:"8019/16 et al.", filed:"2014-06-13", year:"2014", status:"decided", statusLabel:"satisfaction pending", theme:["civilian"], amount:null, amountLbl:"", note:"The largest human-rights case in European history.", milestones:[["2023-01-25","Admissibility",false],["2025-07-09","Merits — Russia liable for MH17",true]]},
  {fol:6, name:"Ukraine v Russia (VIII)", italic:"The Kerch Strait incident (Nov 2018)", forum:"ECtHR", forumLabel:"ECtHR", docket:"55855/18", filed:"2018-11-29", year:"2018", status:"pending", statusLabel:"pending", theme:["territory"], amount:null, amountLbl:"", note:"", milestones:[["2018-11-29","Application filed",true]]},
  {fol:7, name:"Ukraine v Russia (IX)", italic:"Targeted killings abroad — transnational repression", forum:"ECtHR", forumLabel:"ECtHR", docket:"10691/21", filed:"2021-02-19", year:"2021", status:"pending", statusLabel:"pending", theme:["civilian"], amount:null, amountLbl:"", note:"", milestones:[]},
  {fol:8, name:"Russia v Ukraine", italic:"Counter-application, struck out after CoE expulsion", forum:"ECtHR", forumLabel:"ECtHR", docket:"36958/21", filed:"2021-07-22", year:"2021", status:"struck", statusLabel:"struck out 2023", theme:[], amount:null, amountLbl:"", note:"Russia ceased to be a Contracting Party.", milestones:[["2022-09-16","Russia expelled from CoE",false],["2023-07-18","Struck out",true]]},
  {fol:9, name:"Situation in Ukraine", italic:"ICC investigation referred by 43 states parties", forum:"ICC", forumLabel:"ICC", docket:"Sit. UA", filed:"2022-03-02", year:"2022", status:"pending", statusLabel:"investigation active", theme:["civilian"], amount:null, amountLbl:"", note:"Six arrest warrants flow from this investigation.", milestones:[["2022-03-02","43 states parties refer situation",true]]},
  {fol:10, name:"Prosecutor v Putin", italic:"Arrest warrant — President of the Russian Federation", forum:"ICC", forumLabel:"ICC", docket:"PTC II", filed:"2023-03-17", year:"2023", status:"pending", statusLabel:"warrant outstanding", theme:["civilian"], amount:null, amountLbl:"", note:"First ICC warrant against a sitting P5 head of state.", milestones:[["2023-03-17","Warrant issued",true]]},
  {fol:11, name:"Prosecutor v Lvova-Belova", italic:"Russian Children's Commissioner", forum:"ICC", forumLabel:"ICC", docket:"PTC II", filed:"2023-03-17", year:"2023", status:"pending", statusLabel:"warrant outstanding", theme:["civilian"], amount:null, amountLbl:"", note:"Same charges as Putin: deportation and transfer of Ukrainian children.", milestones:[["2023-03-17","Warrant issued",true]]},
  {fol:12, name:"Prosecutor v Kobylash", italic:"Russian Long-Range Aviation commander", forum:"ICC", forumLabel:"ICC", docket:"PTC", filed:"2024-03-05", year:"2024", status:"pending", statusLabel:"warrant outstanding", theme:["civilian"], amount:null, amountLbl:"", note:"", milestones:[["2024-03-05","Warrant issued",true]]},
  {fol:13, name:"Prosecutor v Sokolov", italic:"Black Sea Fleet commander", forum:"ICC", forumLabel:"ICC", docket:"PTC", filed:"2024-03-05", year:"2024", status:"pending", statusLabel:"warrant outstanding", theme:["civilian"], amount:null, amountLbl:"", note:"", milestones:[["2024-03-05","Warrant issued",true]]},
  {fol:14, name:"Prosecutor v Shoigu", italic:"Then-Minister of Defence", forum:"ICC", forumLabel:"ICC", docket:"PTC", filed:"2024-06-24", year:"2024", status:"pending", statusLabel:"warrant outstanding", theme:["civilian"], amount:null, amountLbl:"", note:"", milestones:[["2024-06-24","Warrant issued",true]]},
  {fol:15, name:"Prosecutor v Gerasimov", italic:"Chief of the General Staff", forum:"ICC", forumLabel:"ICC", docket:"PTC", filed:"2024-06-24", year:"2024", status:"pending", statusLabel:"warrant outstanding", theme:["civilian"], amount:null, amountLbl:"", note:"", milestones:[["2024-06-24","Warrant issued",true]]},
  {fol:16, name:"Detention of Ukrainian Naval Vessels", italic:"ITLOS provisional measures + Annex VII (PCA)", forum:"ITLOS", forumLabel:"ITLOS", docket:"ITLOS 26", filed:"2019-04-16", year:"2019", status:"pending", statusLabel:"merits pending", theme:["territory"], amount:null, amountLbl:"", note:"Russia's 'military activities' defence rejected.", milestones:[["2019-05-25","Provisional measures: Russia must release",false],["2019-09","Vessels and crew released",true],["2022-06-27","Annex VII Award on Preliminary Objections",false]]},
  {fol:17, name:"Australia & Netherlands v Russia (MH17)", italic:"ICAO Council, Article 84", forum:"ICAO", forumLabel:"ICAO", docket:"Art. 84", filed:"2022-03-14", year:"2022", status:"decided", statusLabel:"decided · on appeal", theme:["civilian"], amount:null, amountLbl:"", note:"First Article 84 merits ruling in 80 years of ICAO history.", milestones:[["2025-05-12","Council vote — Russia responsible",false],["2025-06-30","Formal decision",true],["2025-09-18","Russia appeals to ICJ",false]]},
  {fol:18, name:"Naftogaz v Gazprom — Supply", italic:"SCC Stockholm — gas supply contract", forum:"SCC", forumLabel:"SCC", docket:"V 2014-078", filed:"2014-06-01", year:"2014", status:"decided", statusLabel:"settled 2019", theme:["money"], amount:-2020000000, amountLbl:"−$2.02b", note:"Netted against the transit award.", milestones:[["2017-12-22","Final award",true]]},
  {fol:19, name:"Naftogaz v Gazprom — Transit", italic:"SCC Stockholm — gas transit contract", forum:"SCC", forumLabel:"SCC", docket:"V 2014-129", filed:"2014-10-01", year:"2014", status:"decided", statusLabel:"settled 2019", theme:["money"], amount:4630000000, amountLbl:"$4.63b", note:"Net $2.56b after offset; ~$2.1b paid before settlement.", milestones:[["2018-02-28","Final award",true],["2019-12-20","Berlin trilateral settlement",false]]},
  {fol:20, name:"Naftogaz v Gazprom (III)", italic:"ICC arbitration — Sokhranivka force-majeure transit", forum:"ICC arb", forumLabel:"ICC arb", docket:"27245/GL", filed:"2022-09-09", year:"2022", status:"decided", statusLabel:"final & confirmed", theme:["money"], amount:1370000000, amountLbl:"$1.37b", note:"First major arbitral win triggered by the full-scale invasion.", milestones:[["2025-06-20","Final award",true],["2026-03","Swiss Federal Tribunal confirms",false]]},
  {fol:21, name:"Naftogaz et al. v Russia", italic:"PCA — Crimean oil & gas expropriation", forum:"PCA", forumLabel:"PCA", docket:"2017-16", filed:"2016-10-17", year:"2016", status:"enforcing", statusLabel:"enforcing in 5 jurisdictions", theme:["money","territory"], amount:5000000000, amountLbl:"$5.00b", gilt:true, note:"Paris, London, Helsinki, Vienna, US — five-front enforcement.", milestones:[["2019-02-22","Partial award — jurisdiction & merits",false],["2023-04-12","Final award",true],["2024-12-06","Hoge Raad confirms",false],["2025-04-01","Paris exequatur",false]]},
  {fol:22, name:"Aeroport Belbek + Kolomoisky v Russia", italic:"PCA — Sevastopol airport", forum:"PCA", forumLabel:"PCA", docket:"2015-07", filed:"2015-01-13", year:"2015", status:"decided", statusLabel:"liability final, quantum pending", theme:["territory","money"], amount:null, amountLbl:"", note:"", milestones:[["2017-02-24","Award on jurisdiction",false],["2024-12-06","Hoge Raad confirms",true]]},
  {fol:23, name:"PrivatBank + Finilon v Russia", italic:"PCA — Crimean banking operations", forum:"PCA", forumLabel:"PCA", docket:"2015-21", filed:"2015-04-13", year:"2015", status:"decided", statusLabel:"liability final, quantum pending", theme:["money","territory"], amount:1000000000, amountLbl:"$1.0b cl.", note:"Quantum claimed.", milestones:[["2019-02-04","Liability award",false],["2024-12-06","Hoge Raad confirms",true]]},
  {fol:24, name:"Oschadbank v Russia", italic:"PCA · Paris-seated — Crimean banking branch", forum:"PCA", forumLabel:"PCA", docket:"2016-14", filed:"2016-01-20", year:"2016", status:"enforcing", statusLabel:"enforcing in France", theme:["money","territory"], amount:1100000000, amountLbl:"$1.10b", note:"~$99m of Russian assets seized in France.", milestones:[["2018-11-26","Award",true],["2022-12-07","Cour de cassation quashes earlier annulment",false],["2025-07-01","Paris CoA confirms award",false]]},
  {fol:25, name:"Ukrnafta v Russia", italic:"PCA · Geneva — 16 petrol stations in Crimea", forum:"PCA", forumLabel:"PCA", docket:"2015-34", filed:"2015-06-15", year:"2015", status:"decided", statusLabel:"final and binding", theme:["money","territory"], amount:44455012, amountLbl:"$44.5m", note:"Swiss FT — first to confirm BIT covers Crimea-located investments.", milestones:[["2018-10-16","Swiss FT confirms jurisdiction",true],["2019-04-12","Final award",false]]},
  {fol:26, name:"Stabil et al. v Russia", italic:"PCA · Geneva — 31 petrol stations", forum:"PCA", forumLabel:"PCA", docket:"2015-35", filed:"2015-06-15", year:"2015", status:"decided", statusLabel:"final and binding", theme:["money","territory"], amount:34600000, amountLbl:"$34.6m", note:"", milestones:[["2019-04-12","Final award",true]]},
  {fol:27, name:"Everest Estate et al. v Russia", italic:"PCA — Crimean real estate", forum:"PCA", forumLabel:"PCA", docket:"2015-36", filed:"2015-06-19", year:"2015", status:"pending", statusLabel:"set-aside remanded", theme:["money","territory"], amount:159000000, amountLbl:"$159m", note:"Only Crimea case the Hoge Raad has remanded.", milestones:[["2018-05-02","Award on merits",false],["2024-12-06","Hoge Raad remands to Amsterdam",true]]},
  {fol:28, name:"Lugzor et al. v Russia", italic:"PCA — Crimean real estate (5 claimants)", forum:"PCA", forumLabel:"PCA", docket:"2015-29", filed:"2015-05-26", year:"2015", status:"decided", statusLabel:"award rendered", theme:["money","territory"], amount:null, amountLbl:"undisc.", note:"", milestones:[["2022-10-04","Award",true]]},
  {fol:29, name:"DTEK Krymenergo v Russia", italic:"PCA — Crimean electricity grid", forum:"PCA", forumLabel:"PCA", docket:"2018-41", filed:"2018-01-01", year:"2018", status:"pending", statusLabel:"UK enforcement stayed", theme:["money","territory"], amount:207800000, amountLbl:"$208m", note:"", milestones:[["2023-11-01","Final award",false],["2025-05-02","UK High Court stays enforcement",true]]},
  {fol:30, name:"NEK Ukrenergo v Russia", italic:"PCA · Paris — Crimean transmission grid", forum:"PCA", forumLabel:"PCA", docket:"Paris-seated", filed:"2020-11-01", year:"2020", status:"pending", statusLabel:"merits phase", theme:["money","territory"], amount:580000000, amountLbl:"€527m cl.", note:"", milestones:[["2024-08-05","Award on jurisdiction confirmed",true]]},
  {fol:31, name:"Energoatom v Russia (II)", italic:"Notice of dispute — Zaporizhzhia NPP", forum:"PCA", forumLabel:"PCA", docket:"TBD", filed:"2023-03-01", year:"2023", status:"pending", statusLabel:"pre-arbitration", theme:["money","territory"], amount:3000000000, amountLbl:"$3b cl.", note:"", milestones:[["2023-03","Notice of dispute",true]]},
  {fol:32, name:"Ukrhydroenergo v Russia", italic:"Notice of dispute — Kakhovka HPP", forum:"PCA", forumLabel:"PCA", docket:"TBD", filed:"2024-06-06", year:"2024", status:"pending", statusLabel:"pre-arbitration paused", theme:["money","civilian"], amount:2500000000, amountLbl:"$2.5b cl.", note:"", milestones:[["2024-06-06","Notice of dispute",true],["2024-10","Tender cancelled",false]]},
  {fol:33, name:"PPS v Girkin, Dubinskiy, Pulatov, Kharchenko", italic:"NL · The Hague — MH17 criminal trial", forum:"Domestic", forumLabel:"NL", docket:"ECLI:NL:RBDHA", filed:"2020-03-09", year:"2020", status:"decided", statusLabel:"verdicts irrevocable", theme:["civilian"], amount:null, amountLbl:"", note:"~€16m in damages joined to the criminal proceedings.", milestones:[["2022-11-17","Verdict — 3 convicted in absentia (life)",true],["2022-12-01","Prosecution declines to appeal Pulatov",false]]},
  {fol:34, name:"JIT MH17 follow-on", italic:"NL · Joint Investigation Team", forum:"Domestic", forumLabel:"NL", docket:"JIT MH17", filed:"2014-08-01", year:"2014", status:"pending", statusLabel:"suspended", theme:["civilian"], amount:null, amountLbl:"", note:"Identified Putin's 'active role' but no immunity waiver.", milestones:[["2023-02-08","JIT suspends — leads exhausted",true]]},
  {fol:35, name:"Russia v Naftogaz et al.", italic:"NL · Hoge Raad — set-aside cassation", forum:"Domestic", forumLabel:"NL · HR", docket:"HR:2024:1810", filed:"2023-01-01", year:"2023", status:"decided", statusLabel:"award stands", theme:["money"], amount:null, amountLbl:"", note:"", milestones:[["2024-12-06","Hoge Raad dismisses cassation",true]]},
  {fol:36, name:"Russia v Belbek/Kolomoisky", italic:"NL · Hoge Raad — set-aside cassation", forum:"Domestic", forumLabel:"NL · HR", docket:"HR 2024", filed:"2022-01-01", year:"2022", status:"decided", statusLabel:"award stands", theme:["money"], amount:null, amountLbl:"", note:"", milestones:[["2024-12-06","Hoge Raad dismisses",true]]},
  {fol:37, name:"Russia v PrivatBank/Finilon", italic:"NL · Hoge Raad — set-aside cassation", forum:"Domestic", forumLabel:"NL · HR", docket:"HR 2024", filed:"2022-01-01", year:"2022", status:"decided", statusLabel:"award stands", theme:["money"], amount:null, amountLbl:"", note:"", milestones:[["2024-12-06","Hoge Raad dismisses",true]]},
  {fol:38, name:"Russia v Everest Estate", italic:"NL · Hoge Raad — remanded to Amsterdam CoA", forum:"Domestic", forumLabel:"NL · HR", docket:"HR 2024", filed:"2022-01-01", year:"2022", status:"pending", statusLabel:"remanded", theme:["money"], amount:null, amountLbl:"", note:"Only Crimea case the Hoge Raad partly opened up.", milestones:[["2024-12-06","Hoge Raad remands",true]]},
  {fol:39, name:"Finland v Yan Petrovsky", italic:"FI · Helsinki — universal jurisdiction", forum:"Domestic", forumLabel:"FI", docket:"Helsinki", filed:"2024-12-01", year:"2024", status:"pending", statusLabel:"appeal pending", theme:["civilian"], amount:null, amountLbl:"", note:"First UJ conviction worldwide of a mercenary-group member for Ukraine war crimes.", milestones:[["2025-03-14","Conviction — life imprisonment",true]]},
  {fol:40, name:"Lithuania v Gadzhimagomedov", italic:"LT · Vilnius — universal jurisdiction", forum:"Domestic", forumLabel:"LT", docket:"Vilnius", filed:"2025-10-30", year:"2025", status:"pending", statusLabel:"pre-trial detention", theme:["civilian"], amount:null, amountLbl:"", note:"First Ukrainian extradition to a third state for prosecution.", milestones:[["2025-10-28","Suspect transferred from Ukrainian custody",true]]},
  {fol:41, name:"EU/Belgium · Russian Central Bank assets", italic:"€210bn immobilised at Euroclear", forum:"Domestic", forumLabel:"EU·BE", docket:"EU Council", filed:"2022-02-28", year:"2022", status:"pending", statusLabel:"frozen indefinitely", theme:["money"], amount:210000000000, amountLbl:"€210b", gilt:true, note:"The single largest pool of Russian state money under European control.", milestones:[["2024-05","Windfall profits regulation 2024/1469",false],["2025-12-12","EU agrees indefinite freeze",true]]}
];

window.forumBucket = (c) => {
  if (c.forum === 'ICJ') return 'ICJ';
  if (c.forum === 'ECtHR') return 'ECtHR';
  if (c.forum === 'ICC') return 'ICC';
  if (c.forum === 'PCA') return 'PCA';
  if (c.forum === 'SCC' || c.forum === 'ICC arb') return 'SCC';
  if (c.forum === 'ITLOS' || c.forum === 'ICAO') return 'ITLOS';
  return 'Domestic';
};

window.formatDate = (iso) => {
  if (!iso || iso.length < 7) return iso || '';
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  if (iso.length <= 7) return d.toLocaleString('en-GB',{month:'short',year:'numeric'});
  return d.toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric'});
};
